name: "Git Tag"
description: "Create and push a git tag"
inputs:
  tag:
    description: "The tag name to create and push"
    required: true
  github_token:
    description: "GitHub token for git tag. Use a PAT to trigger subsequent workflows."
    required: true
runs:
  using: "composite"
  steps:
    - name: Tag and Push
      shell: bash
      env:
        INPUT_TAG: ${{ inputs.tag }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        "${{ github.action_path }}/scripts/tag.sh"
